### ISSUE TITLE
border-radius

### ISSUE THREAD

**Issue by Doniyorbek-Coder** [otabek-oktamov/Namanganliklar-24#3]
https://github.com/otabek-oktamov/Namanganliklar-24/blob/cb2fb1e6f48c327c8ea41b47049521aeb2e0c1f9/styles.css#L22
![image](https://user-images.githubusercontent.com/79502140/111115312-3bc7e500-8586-11eb-802e-c3dcbce6ffba.png)
border-radius: 5px;

**Comment by otabek-oktamov** [comment]
thanks
